AWSTemplateFormatVersion: 2010-09-09
Description: Lab-002 - Adding Rules to Security Groups 
Resources:
  SGIngressHTTP:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: <GROUP ID>
      IpProtocol: tcp
      FromPort: '80'
      ToPort: '80'
      CidrIp: "0.0.0.0/0"
