AWSTemplateFormatVersion: "2010-09-09"
Description: Lab-002 - Creating Security Group
Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Application layer
      GroupName: app-<YOUR NAME>
