AWSTemplateFormatVersion: "2010-09-09"
Description: Application Security Group
Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Application layer
      GroupName: app
