AWSTemplateFormatVersion: '2010-09-09'
Description: Lab-001 - Create a CloudFormation Stack to Provision a S3 bucket Resource
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Lab-001: S3 Bucket"
        Parameters:
          - pS3BucketName

    ParameterLabels:
      pS3BucketName:
        default: "Bucket Name"

Parameters:
  pS3BucketName:
    Description: Name of bucket, must be globally unique.
    Type: String
    Default: pg19.<YOUR NAME>

Resources:
  usecaseBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Ref pS3BucketName

Outputs:
  BucketName:
    Value: !Ref pS3BucketName
    Description: Name of the Amazon S3 bucket for Lab-001
